version: '3.8'

services:
  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    command: [--config=/etc/otel-collector-config.yml]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - 1888:1888 # pprof extension
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Wep App
      - "14268:14268" # Telemetry
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
