receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "*"
          allowed_headers:
            - "*"


processors:
  batch:

exporters:
  logging: # This will make the collector also log to console for debugging
    loglevel: debug
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  datadog:
    api:
      site: datadoghq.eu
      key: <YOUR API KEY>


extensions: # TODO: Check functionality of extensions
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, logging, datadog]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, datadog]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, datadog]
